[package]
name = "atac"
description = "Arguably a Terminal API Client"
version = "0.10.1"
edition = "2021"
authors = ["julien-cpsn"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.26", default-features = false, features = ["cookies", "rustls-tls-native-roots", "multipart", "gzip", "brotli", "deflate"] }
reqwest_cookie_store = "0.6.0"
cookie_store = "0.20.0"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
strum = "0.26.2"
ratatui = "0.26.1"
crossterm = "0.27.0"
tui-big-text = "0.4.2"
tui-textarea = { version = "0.4.0", features = ["ratatui"] }
tui-tree-widget = "0.19.0"
throbber-widgets-tui = { version = "0.4.1", features = ["ratatui"] }
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive", "rc"] }
serde_json = "1.0.114"
toml = "0.8.11"
postman_collection = { git = "https://github.com/Julien-cpsn/postman-collection-rs.git", rev = "6bf3ec87" }
clap = { version = "4.5.0", features = ["derive", "color"] }
lazy_static = "1.4.0"
envfile = "0.2.1"
syntect = "5.2.0"
